In [1]:
import numpy as np
x = range(25)
x = np.reshape(x,(5,5))

print (x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [4]:
x[1:3, 2:4]

array([[ 7,  8],
       [12, 13]])

In [4]:
y = np.zeros_like(x)

In [5]:
y

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])